### PR TITLE
Complete Dashboard and Notifications

### LINKED ISSUE #34: [Feature 13] - Create Dashboard Frontend

### PR DESCRIPTION
**Pull request by ArihantBapna**
Created Dashboard page and Notifications page.

### CODE REVIEW

**Review by vidhip30 — APPROVED** [review]
Looks good

**Review by Tanvipatel9 — APPROVED** [review]
great work!

**Review by hongzipkim — APPROVED** [review]
Looks amazing to me! Thank you Ari!

**Review by hongzipkim — APPROVED** [review]
Looks amazing to me! Thank you Ari!

**Pull request merged**
