### PR TITLE
Upgrade client/server interface implementation for frontend in main branch

### LINKED ISSUE #7: [Feature 1] User Profiles
A page with recommendations (a post) made by the users, along with basic social media information (e.g. follower, following)

### PR DESCRIPTION
**Pull request by iahuang**

### CODE REVIEW

**Review by ArihantBapna — DISMISSED** [review]
Looks good to me

**Review by ArihantBapna — APPROVED** [review]
Looks good to me

**Review by Tanvipatel9 — APPROVED** [review]
seems good

**Review by hongzipkim — APPROVED** [review]
Looks great to me! Thank you Ian!

**Pull request merged**
